### ISSUE TITLE
something wrong with the parameters when config the BLSTM 

### ISSUE THREAD

**Issue by hongyuK** [johnb110/VDPython#1]
There is a ValueError when I git down all the code and run the code follow the guidance.
Traceback is follow:
---
Traceback (most recent call last):                                                                                                                        File "vuldeepecker.py", line 100, in <module>                                                                                                           main()                                                                                                                                                File "vuldeepecker.py", line 95, in main                                                                                                                  blstm = BLSTM(df,name=base)                                                                                                                           File "D:\vuldetect\dataset\VulDeePecker-master\VDPython-master\blstm.py", line 40, in __init__                                                            test_size=0.2, stratify=labels[resampled_idxs])                                                                                                       File "F:\Anaconda\envs\tensorflow\lib\site-packages\sklearn\model_selection\_split.py", line 2100, in train_test_split                                  
  default_test_size=0.25)                                                                                                                               File "F:\Anaconda\envs\tensorflow\lib\site-packages\sklearn\model_selection\_split.py", line 1782, in _validate_shuffle_split                           
  train_size)                                                                                                                                         ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by ckt0325** [comment]
I found an error in lines 32 and 33 of blstm.py.
 The data of vectors and labels are reversed.
```
vectors = np.stack(data.iloc[:, 1].values)             0
labels = data.iloc[:, 0].values                              1 
```

**Comment by lyqssb** [comment]
I got the same error 
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
Don't know how to fix it? @ckt0325  have you correct it?

**Comment by ckt0325** [comment]
Vectors is the first column of data, labels is the second column of data.

Original codes:
vectors = np.stack(data.iloc[:, 1].values)
labels = data.iloc[:, 0].values
Modified codes:
vectors = np.stack(data.iloc[:, 0].values)
labels = data.iloc[:, 1].values
Hope my advice can help you.
@lyqssb

**Comment by ckt0325** [comment]
Vectors is the first column of data, labels is the second column of data.&nbsp;



Original codes:
vectors = np.stack(data.iloc[:, 1].values)
labels = data.iloc[:, 0].values
Modified codes:
vectors = np.stack(data.iloc[:, 0].values)
labels = data.iloc[:, 1].values
Hope my advice can help you.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyqssb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 下午2:57
收件人:&nbsp;"johnb110/VDPython"<VDPython@noreply.github.com&gt;;
抄送:&nbsp;"David"<2898984956@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [johnb110/VDPython] something wrong with the parameters when config the BLSTM  (#1)





 
I got the same error
 ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
 Don't know how to fix it? @ckt0325  have you correct it?

**Comment by lyqssb** [comment]
@ckt0325  it works now ! thank you so much!!!!

**Comment by ckt0325** [comment]
You are welcome. I once read this code, if you have any problem, we can study it together.
And this is my email: 2898984956@qq.com


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyqssb"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 下午3:26
收件人:&nbsp;"johnb110/VDPython"<VDPython@noreply.github.com&gt;;
抄送:&nbsp;"David"<2898984956@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [johnb110/VDPython] something wrong with the parameters when config the BLSTM  (#1)





 
@ckt0325  it works now ! thank you so much!!!!

**Comment by lyqssb** [comment]
@ckt0325 My pleasure~ thanks!

**Comment by catch22out** [comment]
Traceback (most recent call last):
  File "D:\VDPython-master\vuldeepecker.py", line 100, in <module>
    main()
  File "D:\VDPython-master\vuldeepecker.py", line 95, in main
    blstm = BLSTM(df,name=base)
  File "D:\VDPython-master\blstm.py", line 40, in __init__
    test_size=0.2, stratify=labels[resampled_idxs])
  File "D:\Program Files\Python37\lib\site-packages\sklearn\model_selection\_split.py", line 2122, in train_test_split
    default_test_size=0.25)
  File "D:\Program Files\Python37\lib\site-packages\sklearn\model_selection\_split.py", line 1805, in _validate_shuffle_split
    train_size)
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

The same question as you @hongyuK
So how do you work it out?

**Comment by lily79** [comment]
> Vectors is the first column of data, labels is the second column of data.
> 
> Original codes:
> vectors = np.stack(data.iloc[:, 1].values)
> labels = data.iloc[:, 0].values
> Modified codes:
> vectors = np.stack(data.iloc[:, 0].values)
> labels = data.iloc[:, 1].values
> Hope my advice can help you.
> @lyqssb

看你留的联系方式是qq，所以猜你也是国内的哈，就用中文说了，我也发现了这个问题，也是按照你一样改的，改完调试还是会报错，报的错误是：
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/tmp/pycharm_project_295/vuldeepecker.py", line 101, in <module>
    main()
  File "/tmp/pycharm_project_295/vuldeepecker.py", line 97, in main
    blstm.train()
  File "/tmp/pycharm_project_295/blstm.py", line 75, in train
    self.model.fit(self.X_train, self.y_train, batch_size=self.batch_size, epochs=4, class_weight=self.class_weight)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 802, in fit
    data_handler = data_adapter.DataHandler(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1116, in __init__
    if class_weight:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

你遇到这个问题了没？你是咋改的？谢谢啦！
我的联系方式35248934，申请加你了
@ckt0325

**Comment by lily79** [comment]
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

解决了，有人遇到了一样的问题，应该是class_weights参数用错，当其是一个 numpy array的时候，用 sample_weight参数穿这个值，不要用 class_weight 这个参数，在keras的_make_class_weight_map_fn函数里，class_weight接受的是字典对象。
https://stackoverflow.com/questions/62913700/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

**Comment by lily79** [comment]
> > ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 
> 解决了，有人遇到了一样的问题，应该是class_weights参数用错，当其是一个 numpy array的时候，用 sample_weight参数穿这个值，不要用 class_weight 这个参数，在keras的_make_class_weight_map_fn函数里，class_weight接受的是字典对象。
> https://stackoverflow.com/questions/62913700/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

这么改还是会报错，所以，直接把class_weight改为字典类型传进去：
self.model.fit(self.X_train, self.y_train, batch_size=self.batch_size, epochs=4, class_weight=self.class_weight)
改为：
self.model.fit(self.X_train, self.y_train, batch_size=self.batch_size, epochs=4, class_weight=dict(enumerate(self.class_weight)))
解决啦！

**Comment by foresta-yang** [comment]
> > ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
> 
> 解决了，有人遇到了一样的问题，应该是class_weights参数用错，当其是一个 numpy array的时候，用 sample_weight参数穿这个值，不要用 class_weight 这个参数，在keras的_make_class_weight_map_fn函数里，class_weight接受的是字典对象。 https://stackoverflow.com/questions/62913700/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous

好兄弟，这问题至少都可以解决，我想知道最关键的，他的源码里面没有获取code_gadget的代码，怎么从源代码提取code_gadget的方法并没有，复现出来的结果没办法用在新数据集中，好头疼啊。您那边有这个提取code_gadget的方法吗？
